services:
  hhvm:
    container_name: theodore-svg-stream-namespaced-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 127.0.0.1::10641
